# ═══════════════════════════════════════════════════════════════
# Flutter/Dart Rules Configuration
# ═══════════════════════════════════════════════════════════════
# 
# هذا الملف يتيح لك تخصيص القواعد حسب احتياجات مشروعك
# 
# مستويات التفعيل:
#   - true: مفعل
#   - false: معطل
#   - enforce: مفعل مع تشديد (يمنع build في حالة الخطأ)
#   - warn: مفعل كتحذير فقط
#
# ═══════════════════════════════════════════════════════════════

# معلومات المشروع
project:
  name: "my_flutter_app"
  version: "1.0.0"
  type: mobile  # Options: mobile, web, desktop, multi-platform
  team_size: small  # Options: solo, small (2-5), medium (6-15), large (15+)

# إعدادات البيئة
environment:
  dart_sdk: ">=3.9.2 <4.0.0"  # ✅ Updated to Dart 3.9.2 (Latest Stable - Aug 2025)
  flutter_sdk: ">=3.35.0"  # ✅ Updated to Flutter 3.35.0 (Latest Stable - Aug 2025)
  platforms:
    android: true
    ios: true
    web: false
    windows: false
    macos: false
    linux: false

# ═══════════════════════════════════════════════════════════════
# 🔴 CORE RULES (إلزامية - لا يمكن تعطيلها)
# ═══════════════════════════════════════════════════════════════
core:
  enabled: true
  strict_mode: true  # إذا كان false، يحول الأخطاء إلى تحذيرات
  
  # Null Safety
  null_safety:
    enabled: enforce
    avoid_bang_operator: warn  # تجنب ! إلا عند الضرورة
    
  # Error Handling
  error_handling:
    no_silent_errors: enforce
    use_try_catch: true
    custom_exceptions: true
    
  # Code Style
  code_style:
    naming_conventions:
      pascal_case_classes: enforce
      camel_case_members: enforce
      snake_case_files: enforce
    line_length: 120  # Options: 80, 100, 120
    function_max_lines: 20
    avoid_abbreviations: warn
    
  # Async/Await
  async_await:
    proper_error_handling: enforce
    use_futures: true
    use_streams: true
    
  # Logging
  logging:
    use_logging_package: true
    avoid_print: enforce  # لا تستخدم print() في production

# ═══════════════════════════════════════════════════════════════
# 🟡 FLUTTER BASICS (موصى بها بشدة)
# ═══════════════════════════════════════════════════════════════
flutter_basics:
  enabled: true
  
  # Widgets
  widgets:
    immutability: enforce
    prefer_stateless: true
    composition_over_inheritance: true
    private_widget_classes: true  # استخدم widget classes بدلاً من helper methods
    
  # Performance
  performance:
    use_const_constructors: enforce
    listview_builder_for_long_lists: enforce
    avoid_expensive_ops_in_build: enforce
    use_compute_for_heavy_tasks: true
    isolates:
      enabled: true
      threshold_ms: 16  # استخدم isolate إذا تجاوزت المهمة 16ms
  
  # Build Method
  build_method:
    break_down_large_builds: true
    max_lines: 100  # حدد build method في 100 سطر
    extract_widgets: true

# ═══════════════════════════════════════════════════════════════
# 🏗️ ARCHITECTURE (اختياري حسب حجم المشروع)
# ═══════════════════════════════════════════════════════════════
architecture:
  enabled: true
  pattern: layered  # Options: layered, mvvm, clean, feature-based, none
  
  # Layered Architecture
  layered:
    enabled: true
    layers:
      presentation: true
      domain: true
      data: true
      core: true
    enforce_separation: warn  # تحذير عند استيراد layer خاطئ
    
  # MVVM Pattern
  mvvm:
    enabled: false
    view_models:
      use_change_notifier: true
      dependency_injection: manual  # Options: manual, provider, get_it
      
  # Clean Architecture
  clean_architecture:
    enabled: false
    enforce_dependency_rule: false  # Domain لا يعتمد على Data/Presentation
    
  # Feature-based Organization
  feature_based:
    enabled: false  # مفيد للمشاريع الكبيرة
    min_features: 5  # ابدأ feature-based عند 5 features أو أكثر

# ═══════════════════════════════════════════════════════════════
# 🔄 STATE MANAGEMENT
# ═══════════════════════════════════════════════════════════════
state_management:
  # Primary solution
  primary: built-in  # Options: built-in, provider, bloc, riverpod, getx
  allow_multiple: false  # السماح باستخدام أكثر من حل
  
  # Flutter Hooks  # ✅ UPDATED! (2025-10-22)
  hooks:
    enabled: false  # Enable for React-style hooks
    version: "^0.21.3"  # ✅ Updated to 0.21.3 (Latest - Aug 2025)
    use_with: riverpod  # Options: riverpod, standalone
    hooks_riverpod_version: "^3.0.3"  # ✅ Latest stable
    features:
      less_boilerplate: true
      auto_cleanup: true
      custom_hooks: true
    use_for:
      - complex_widgets  # للـ widgets المعقدة
      - reusable_logic  # Logic قابل لإعادة الاستخدام
  
  # Built-in Solutions (الافتراضي)
  built_in:
    enabled: true
    value_notifier: true
    change_notifier: true
    stream_builder: true
    future_builder: true
    listenable_builder: true
    
  # Provider (third-party)
  provider:
    enabled: false
    version: "^6.1.5"  # ✅ Updated to 6.1.5 (Latest - Jan 2025)
    use_cases:
      - dependency_injection
      - complex_state
      
  # Bloc (third-party)
  bloc:
    enabled: false
    version: "^9.1.0"  # ✅ Updated to 9.1.0 (Latest - Jan 2025)
    flutter_bloc_version: "^9.1.1"  # ✅ Updated to 9.1.1 (Latest)
    use_cubit: true  # استخدم Cubit للحالات البسيطة
    
  # Riverpod (third-party)  # ✅ MAJOR UPDATE!
  riverpod:
    enabled: false
    version: "^3.0.3"  # ✅ Latest stable (Aug 2025)
    flutter_riverpod_version: "^3.0.3"  # ✅ Latest stable (Aug 2025)
    riverpod_annotation_version: "^3.0.3"  # ✅ Updated to 3.0.3 (Aug 2025)
    riverpod_generator_version: "^3.0.3"  # ✅ Updated to 3.0.3 (Aug 2025)
    riverpod_lint_version: "^3.0.3"  # ✅ Updated to 3.0.3 (Aug 2025)
    use_code_generation: true  # ✅ Recommended (code generation)
    
  # GetX (third-party)
  getx:
    enabled: false
    version: "^4.7.2"  # ✅ Updated to 4.7.2 (Latest - Aug 2025)
    use_for: []  # Options: state, routing, dependency_injection

# ═══════════════════════════════════════════════════════════════
# 🧭 NAVIGATION & ROUTING
# ═══════════════════════════════════════════════════════════════
navigation:
  router: go_router  # Options: go_router, auto_route, navigator, none
  
  # GoRouter (موصى به)
  go_router:
    enabled: true
    version: "^16.2.5"  # ✅ Latest stable (Aug 2025)
    go_router_builder_version: "^4.1.1"  # ✅ Type-safe routes (Aug 2025)
    use_code_generation: true  # ✅ Recommended for type-safe routes
    features:
      deep_linking: true
      web_support: true
      authentication_redirect: true
      route_guards: true
      typed_routes: true
      
  # AutoRoute
  auto_route:
    enabled: false
    version: "^10.2.0"  # ✅ Updated to 10.2.0 (Latest - Aug 2025)
    use_code_generation: true
    
  # Navigator (built-in)
  navigator:
    use_for_dialogs: true  # استخدم Navigator للـ dialogs فقط
    use_for_bottom_sheets: true

# ═══════════════════════════════════════════════════════════════
# 💾 DATA & SERIALIZATION
# ═══════════════════════════════════════════════════════════════
data:
  # JSON Serialization
  serialization:
    method: json_serializable  # Options: json_serializable, dart_mappable, freezed, built_value, manual
    json_serializable:
      enabled: true
      version: "^6.11.1"  # ✅ Updated to 6.11.1 (Latest - Aug 2025)
      field_rename: snake  # تحويل camelCase إلى snake_case
      explicit_to_json: true
    dart_mappable:  # ✅ UPDATED! (2025-10-22)
      enabled: false  # Enable if you want better performance & features
      version: "^4.6.1"  # ✅ Updated to 4.6.1 (Latest - Aug 2025)
      features:
        polymorphism: true  # دعم كامل للـ inheritance
        copy_with: true  # Auto-generated copyWith
        equality: true  # Built-in equality
      use_for:
        - new_features  # للميزات الجديدة
        - performance_critical  # للأداء العالي
    freezed:
      enabled: false
      version: "^3.2.3"  # ✅ Updated to 3.2.3 (Latest - Aug 2025)
      freezed_annotation_version: "^2.4.4"  # ✅ Latest
      use_with_json_serializable: false
      
  # HTTP Clients
  http_client: dio  # Options: dio, http, retrofit
  dio:
    enabled: true
    version: "^5.9.0"  # ✅ Latest stable (Aug 2025)
    features:
      interceptors: true
      timeout: 30000  # milliseconds
      retry: true
      pretty_logger:  # ✅ NEW!
        enabled: false  # Enable for beautiful logs
        version: "^1.4.0"
        production: false  # Don't use in production
      
  # Local Storage
  local_storage:
    preferences: shared_preferences  # للإعدادات البسيطة
    database: sqflite  # Options: sqflite, hive, objectbox, isar, drift
    cache: hive  # للتخزين المؤقت
    
    objectbox:  # ✅ NEW! (2025-10-22)
      enabled: false  # Enable for ultra-fast database (10x faster than Hive)
      version: "^5.0.0"  # ✅ Updated to 5.0.0 (Latest - Aug 2025)
      features:
        relations: true  # Native relations support
        queries: true  # Powerful query API
        sync: false  # Cloud sync (optional)
      use_for:
        - high_performance  # عند الحاجة لأداء عالي
        - complex_relations  # علاقات معقدة
        - real_time  # تطبيقات real-time
    
  # Caching Strategy
  caching:
    enabled: true
    cache_duration: 3600  # seconds
    cache_images: true
    offline_first: false
  
  # Value Equality  # ✅ NEW! (2025-10-22)
  equality:
    equatable:
      enabled: false  # Enable for easy value equality
      version: "^2.0.7"  # ✅ Latest stable (Aug 2025)
      use_for:
        - models  # جميع الـ models
        - state_classes  # State management classes
        - value_objects  # Value objects

# ═══════════════════════════════════════════════════════════════
# 🎨 UI DESIGN & THEMING
# ═══════════════════════════════════════════════════════════════
ui_design:
  # Material Design
  material_version: 3  # Options: 2, 3
  
  # Theme
  theme:
    use_centralized_theme: enforce
    color_scheme:
      use_from_seed: true
      seed_color: "#6750A4"  # Material 3 default
    dark_mode:
      enabled: true
      follow_system: true
    custom_colors:
      enabled: true
      use_theme_extension: true
    fonts:
      use_google_fonts: true
      primary_font: "Roboto"
      fallback_to_system: true
      
  # Responsive Design
  responsive:
    enabled: true
    breakpoints:
      mobile: 600
      tablet: 900
      desktop: 1200
    use_layout_builder: true
    use_media_query: true
    
  # Typography
  typography:
    enforce_text_theme: true
    scale: material_3  # Options: material_3, custom
    line_height_ratio: 1.5
    max_line_length: 75  # characters للنصوص الطويلة
    
  # Layout Best Practices
  layout:
    use_expanded_in_rows: enforce
    use_listview_builder: enforce
    avoid_overflow: enforce
    use_singlechildscrollview: true
    
  # Visual Design
  visual:
    shadows: true
    animations: true
    icons: true
    images:
      use_cached_network_image: true
      provide_error_builder: enforce
      provide_loading_builder: true

# ═══════════════════════════════════════════════════════════════
# ♿ ACCESSIBILITY (A11Y)
# ═══════════════════════════════════════════════════════════════
accessibility:
  enabled: true
  level: standard  # Options: basic, standard, wcag_aa, wcag_aaa
  
  # Color Contrast
  color_contrast:
    check: true
    min_ratio_normal_text: 4.5  # WCAG AA
    min_ratio_large_text: 3.0
    
  # Semantic Labels
  semantic_labels:
    enforce: warn
    require_for_buttons: true
    require_for_images: true
    
  # Dynamic Text Scaling
  text_scaling:
    test: true
    support_large_fonts: true
    
  # Screen Readers
  screen_readers:
    test_with_talkback: false  # Android
    test_with_voiceover: false  # iOS
    
  # Keyboard Navigation
  keyboard_navigation:
    enabled: false  # مهم للويب والديسكتوب

# ═══════════════════════════════════════════════════════════════
# ✅ TESTING
# ═══════════════════════════════════════════════════════════════
testing:
  required: true
  
  # Test Types
  unit_tests:
    enabled: enforce
    min_coverage: 80  # percentage
    test_pattern: "Arrange-Act-Assert"
    
  widget_tests:
    enabled: enforce
    test_all_screens: true
    test_user_interactions: true
    
  integration_tests:
    enabled: true
    test_critical_flows: true
    
  golden_tests:
    enabled: false  # للـ UI regression testing
    
  # Testing Tools
  tools:
    use_checks_package: true  # بدلاً من matchers
    mocking_strategy: fakes  # Options: fakes, mocks, stubs
    mockito:
      enabled: false
      use_code_generation: false
    mocktail:
      enabled: false
      
  # Test Organization
  organization:
    mirror_lib_structure: true
    separate_integration_tests: true
    
  # Coverage
  coverage:
    enabled: true
    min_threshold: 80
    enforce_threshold: false
    exclude_generated: true

# ═══════════════════════════════════════════════════════════════
# 🛠️ DEVELOPMENT TOOLS
# ═══════════════════════════════════════════════════════════════
tools:
  # Package Management
  package_management:
    auto_upgrade: false
    check_outdated: true
    
  # Code Generation
  code_generation:
    enabled: true
    build_runner:
      version: "^2.10.0"  # ✅ Updated to 2.10.0 (Latest - Aug 2025)
      delete_conflicting_outputs: true
    watch_mode: false  # للتطوير السريع
    
  # Linting
  linting:
    preset: flutter_lints  # Options: flutter_lints, very_good_analysis, custom
    custom_rules:
      - prefer_const_constructors
      - prefer_const_literals_to_create_immutables
      - always_use_package_imports
      - avoid_print
      - avoid_unnecessary_containers
      - sized_box_for_whitespace
      - use_key_in_widget_constructors
    pedantic_mode: false  # تشديد كل القواعد
    
  # Formatting
  formatting:
    use_dart_format: enforce
    line_length: 120
    
  # Documentation
  documentation:
    enforce_dartdoc: warn
    document_public_apis: true
    document_private_apis: false
    include_examples: true
    
  # Git Hooks
  git_hooks:
    pre_commit:
      run_tests: false
      run_linter: true
      run_formatter: true
    pre_push:
      run_tests: true
      check_coverage: false

# ═══════════════════════════════════════════════════════════════
# 🚀 PERFORMANCE & OPTIMIZATION
# ═══════════════════════════════════════════════════════════════
performance:
  # Profiling
  profiling:
    enabled: false
    tools:
      - devtools
      - flutter_performance_overlay
      
  # Build Optimization
  build:
    tree_shake_icons: true
    split_debug_info: true
    obfuscate: false  # للـ production
    
  # Memory Management
  memory:
    monitor_leaks: false
    dispose_controllers: enforce
    cancel_streams: enforce
    
  # Network Optimization
  network:
    cache_responses: true
    compress_requests: true
    use_connection_pooling: true

# ═══════════════════════════════════════════════════════════════
# 🔒 SECURITY
# ═══════════════════════════════════════════════════════════════
security:
  # API Keys
  api_keys:
    use_env_file: true
    never_hardcode: enforce
    use_dart_define: true
    
    envied:  # ✅ NEW! (2025-10-22)
      enabled: false  # Enable for compile-time obfuscation
      version: "^1.3.1"  # ✅ Updated to 1.3.1 (Latest - Aug 2025)
      features:
        obfuscation: true  # Compile-time obfuscation
        type_safe: true  # Type-safe access
        multi_environment: true  # dev/prod environments
      use_for:
        - sensitive_data  # API keys, secrets
        - ci_cd  # Integration with CI/CD
    
  # Data Security
  data:
    encrypt_sensitive_data: false
    secure_storage: false  # استخدم flutter_secure_storage
    
  # Network Security
  network:
    use_https_only: enforce
    certificate_pinning: false
    
  # Authentication
  authentication:
    implement_auth_flow: false
    secure_token_storage: false
    auto_logout: false

# ═══════════════════════════════════════════════════════════════
# 📝 LOGGING & MONITORING
# ═══════════════════════════════════════════════════════════════
logging:
  # Logging Package  # ✅ UPDATED! (2025-10-22)
  package: talker  # Options: logger, talker, dart_developer_log
  
  talker:  # ✅ NEW! (2025-10-22)
    enabled: false  # Enable for professional logging
    version: "^5.0.2"  # ✅ Updated to 5.0.2 (Latest - Aug 2025)
    features:
      flutter_integration: true  # In-app logs viewer
      dio_logger: false  # HTTP logs
      riverpod_logger: false  # Riverpod logs
      custom_colors: true
      export_logs: true  # Share/Export for bug reports
    use_for:
      - production  # موصى به للـ production
      - debugging  # تسهيل الـ debugging
      - bug_reports  # جمع logs للـ bug reports
  
  # Development Logging
  development:
    use_dart_developer_log: true
    log_level: debug  # Options: debug, info, warning, error
    structured_logging: true
    
  # Production Logging
  production:
    log_level: error
    
  # Error Tracking
  error_tracking:
    enabled: false
    service: none  # Options: firebase_crashlytics, sentry, none
    
  # Analytics
  analytics:
    enabled: false
    service: none  # Options: firebase_analytics, mixpanel, none

# ═══════════════════════════════════════════════════════════════
# 🌍 INTERNATIONALIZATION (i18n)
# ═══════════════════════════════════════════════════════════════
i18n:
  enabled: false
  default_locale: en
  supported_locales:
    - en
    - ar
  use_intl: true
  use_arb_files: true
  rtl_support: false

# ═══════════════════════════════════════════════════════════════
# 🔧 PROJECT-SPECIFIC CUSTOMIZATION
# ═══════════════════════════════════════════════════════════════
custom:
  # قواعد إضافية خاصة بمشروعك
  additional_rules: []
  
  # استثناءات (قواعد تريد تجاهلها)
  excluded_rules: []
  
  # ملاحظات
  notes: |
    أضف أي ملاحظات خاصة بمشروعك هنا
    
  # Team Conventions
  team_conventions:
    code_review_required: true
    pair_programming: false
    documentation_required: true

# ═══════════════════════════════════════════════════════════════
# 📊 PROFILES (إعدادات جاهزة)
# ═══════════════════════════════════════════════════════════════
# يمكنك تفعيل profile جاهز بدلاً من التخصيص اليدوي

profiles:
  # Profile للمشاريع الصغيرة
  small_project:
    enabled: false
    description: "مشروع صغير (1-3 شاشات، مطور واحد)"
    overrides:
      architecture.enabled: false
      state_management.primary: built-in
      navigation.router: navigator
      testing.min_coverage: 60
      
  # Profile للمشاريع المتوسطة
  medium_project:
    enabled: true  # ✅ مفعل
    description: "مشروع متوسط (5-15 شاشة، فريق صغير)"
    overrides:
      architecture.pattern: layered
      state_management.primary: built-in
      navigation.router: go_router
      testing.min_coverage: 75
      
  # Profile للمشاريع الكبيرة
  large_project:
    enabled: false
    description: "مشروع كبير (20+ شاشة، فريق كبير)"
    overrides:
      architecture.pattern: feature-based
      state_management.primary: bloc
      navigation.router: go_router
      testing.min_coverage: 85
      ui_design.responsive.enabled: true
      
  # Profile للـ MVP
  mvp:
    enabled: false
    description: "MVP - التركيز على السرعة"
    overrides:
      architecture.enabled: false
      testing.min_coverage: 40
      code_style.line_length: 120
      performance.profiling.enabled: false
